### ISSUE TITLE
countDebugDexMethods UP-TO-DATE

### ISSUE THREAD

**Issue by will421** [KeepSafe/dexcount-gradle-plugin#131]
Hi,

I use version 0.5.6.
When I run task countDebugDexMethods for the first time it works.
Then, I do some change on my code and run this task again : it is flagged as UP-TO-DATE and does not display dex count.
```
:app:packageDebug
:app:zipalignDebug
:app:assembleDebug
:app:countDebugDexMethods UP-TO-DATE
```

Of course it works if I clean my project.

**Comment by benjamin-bader** [comment]
This happens because the output of `assembleDebug` is a (the only, really) dependency of `countDebugDexMethods`.  Gradle works in such a way that, if all the dependencies of a task are up-to-date, the dependent task is also considered to be up-to-date.

We could change this to always run, and in fact we used to do this, but it kind of goes against the grain, in that it is a misuse of Gradle tasks.

What's curious is that you made code changes, yet Gradle didn't report `assembleDebug` as having a different output.  I'm not positive, but I *think* that it uses mtime and a hash of your APK to determine whether it has changed.  Very strange!  I'll see if I can repro.

How are you building - commandline or Android Studio?  If Android Studio, is Instant Run enabled?

**Comment by will421** [comment]
I'm building on Android Studio with Instant run disabled.
The behavior is the same in commandline.

I'm a beginner in gradle tasks and know nothing in groovy but : Doesn't you need to define un input for UP-TO-DATE check in DexMethodCountTask.groovy ?

**Comment by benjamin-bader** [comment]
Indeed.  You're correct, and I thought that we did have that, but turns out - at some point `@Input` was removed, and I'd forgotten about it!  I removed it in d257189 because, for dumb reasons, using it caused either a crash *or* a failure if the .apk is renamed during the build.

I'm confused about why the dexcount task would be up-to-date when it has no inputs and only outputs; one would think that the task needs to run before output equality can be computed.  I'll investigate.

The way it looks now, we *might* be able to fix your scenario by removing `@Output` and `@OutputDirectory`.  I have no idea if/how that will break existing users.  I'll do some digging.  Thanks for reporting this!

**Comment by will421** [comment]
> I'm confused about why the dexcount task would be up-to-date when it has no inputs and only outputs; one would think that the task needs to run before output equality can be computed. I'll investigate.

AFAIK, a task should be "pure", same input give same output.
We have no input so gradle check only output and will run the task only if output has changed (clean for exemple)
This is what I understood from this : https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:how_does_it_work

**Comment by benjamin-bader** [comment]
That makes sense; I had interpreted that differently at first, but experimenting shows that yours is the correct reading.  It isn't so intuitive that outputs would be considered *before* running a task, but so it goes.

I'll have a release soonish with a fix; there's at least one other thing I want to fit in beforehand.

**Comment by benjamin-bader** [comment]
I just pushed version 0.6.0 to Maven Central, containing this bugfix.  It should be available within 15 minutes, tops.

**Comment by will421** [comment]
Thank you !
