### ISSUE TITLE
Move "dexdeps" in to separate library

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#213]
It looks like the "dexdeps" folder is from here: https://github.com/KeepSafe/dexcount-gradle-plugin/tree/master/src/main/java/com/android/dexdeps

I have created this repository, https://github.com/jaredsburrows/davlik-tools-dexdeps, to be able to pull that code our of this repository. @benjamin-bader What do you think?

The only problem I am seeing, it looks like there has been a few methods added or removed. I was thinking we could either subclass and/or Kotlin extension functions for the extra code that we need for this plugin.

**Comment by benjamin-bader** [comment]
I've made some customizations to this code over the years, both removing unused functionality and adding at least one new interface (HasDeclaringClass, I think?).

Why would we need to make a separate artifact here?

**Comment by jaredsburrows** [comment]
Out of all the files, it looks like `DexData`  was modified, `FieldRef` and `MethodRef` have the `HasDeclaringClass` interface. Other than that, it is just copied and pasted from the Android source code. 

I was just thinking it might be cleaner if we can remove the copied code from this code base.

**Comment by benjamin-bader** [comment]
Clean is also a matter of perspective here; I can see the point that "dexdeps" and "dexcount" do different things, and so would be candidates to split apart.  On the other hand, one could also say that it's cleaner to keep our dependencies in one place.  IMO it's to our advantage to have the files here where they can easily be modified as needed, as has happened several times already.  

Since the sources are already published, I'm not yet sure that I see the use of separating the Java files out into their own artifact.  If there's an artifact to be made, would't it be better to create it based on the original Android sources?

**Comment by jaredsburrows** [comment]
> would't it be better to create it based on the original Android sources?

@benjamin-bader My repo is based on the Android sources.

**Comment by benjamin-bader** [comment]
Sorry, I might have been unclear.  My point was that the dexcount copy is modified for our own purposes, and other projects would be better served by "vanilla" sources.  By the same token, dexcount itself wouldn't see any benefit to using the vanilla sources, because we've already made modifications.

**Comment by jaredsburrows** [comment]
I know they have modifications. I am just saying we could remove the majority of the copy/pasted code out of this repository's source sets and either subclass or use kotlin extensions.

**Comment by benjamin-bader** [comment]
Discussed in-person; our conclusion is that dexcount wouldn't be well-served by this change.  Publishing dexdeps as a separate artifact is awesome, but we won't be using it here.
