### ISSUE TITLE
Ability to not count Kotlin inline fun/val/var

### ISSUE THREAD

**Issue by LouisCAD** [KeepSafe/dexcount-gradle-plugin#241]
Kotlin's `inline` functions and properties are not marked as `@InlineOnly` (`internal` to the stdlib) and are still non inline methods (useful when using the debugger).

However, proguard easily removes them on release builds, so they only count for development, but not for the final apk delivered to users.

It would be helpful to run this dexcount plugin not counting these `inline` `fun`/`val`/`var`, so we can determine the potentially not "shavable-off" methods count.

As an Android library developer who cares about minimizing the weight of his libraries, it would help me to know the real weight of my library methods count wise (even if I don't have a sample app that uses absolutely all the methods of my library on which I could run dexcount).

Would the plugin have the ability to detect `inline` `fun`/`val`/`var` and give an option to not count them?

Anyway, thanks a lot for this very useful gradle plugin!

**Comment by benjamin-bader** [comment]
Hi Louis, thanks for the kind words and for your question.  We don't really see "funs" or "vars" or "vals", because we operate on compiled .dex files.  For this reason, we can't detect (or ignore) Kotlin language features (or Java language features, for that matter).

Your real question, it seems, is how to get an actual count of methods that will end up in your release build.  For that, I think you can simply run the plugin during a release build - it will see the post-proguard APK, and you can then compare those counts with your debug build, and see the difference that way.

**Comment by LouisCAD** [comment]
Hi Benjamin, thanks for your response.

Since you directly work on the dex, I took a look at the Kotlin bytecode for inline and non inline functions, and there's unfortunately no metadata annotation to indicate that one is inline, so I request a feature to add a compiler flag that would make Kotlin's `inline` methods inline only, so that this plugin may use it. https://youtrack.jetbrains.com/issue/KT-23420

Note that enabling proguard doesn't fit my needs because it'd also strip unused non inline methods, which I want to count because I want to know the maximum weight (where **all** the symbols would be used) of my library in a proguarded app.

**Comment by benjamin-bader** [comment]
> [...] I want to know the maximum weight (where all the symbols would be used) of my library in a proguarded app.

Then I agree, there is currently no way to get what you are asking for from this plugin.

I'd also posit that it is not usually very meaningful to establish "maximum weight" prior to inclusion of a library into an app, because "total weight" makes a lot of assumptions about the library consumer that just aren't usually true.  For example, it's very likely that consumers are using things like `java.util`, or the support library, but counting an AAR by itself would include those classes and method references.  The impact of adding this AAR to literally any app would be less than the "total weight" would suggest.  This is why I generally discourage people from counting AARs, or relying on assertions about the size-in-methods of some library in isolation.

Just my two cents - it's of course up to you to know what your true needs are.

In the meantime, it seems that there is no action needed here, so I will close this issue.
