### ISSUE TITLE
error "String index out of range: -1"in a very simple layout

### ISSUE THREAD

**Issue by MostafaSolimanMoma** [KeepSafe/dexcount-gradle-plugin#251]
I added a very simple activity with a very simple layout "just hello world"and when i was trying to run it ,it gave me this error 
`String index out of range: -1`

**Comment by benjamin-bader** [comment]
I can't tell from your description whether this has anything at all to do with `dexcount-gradle-plugin`.  Can you describe the error more?  When do you see it - when building the app, or when running the app?  If it is during your build, can you re-build with `--stacktrace` and post the log?

**Comment by MostafaSolimanMoma** [comment]
when running the app !

**Comment by MostafaSolimanMoma** [comment]
when running the app

**Comment by benjamin-bader** [comment]
So you've got the app installed, you open it, then get that error?

**Comment by benjamin-bader** [comment]
Basically, what I'm getting at, is this - what makes you think this is a dexcount bug?  What prompted you to come to _this_ particular issue tracker?

**Comment by benjamin-bader** [comment]
Hi, were you able to get things working?

**Comment by benjamin-bader** [comment]
Closing due to both non-responsiveness and probably not being anything to do with dexcount.  It's hard for me to tell what problem you're having, because there isn't any detail in the issue.

In the future, it will help people to help you if you can describe things more clearly, like:
- what command (if any) did you run?
- what did you expect to happen?
- what actually happened?
- what unusual output, if any, do you see?
- etc
