### ISSUE TITLE
OutputFormat configuration not clear defined in the documentation

### ISSUE THREAD

**Issue by bekuno** [KeepSafe/dexcount-gradle-plugin#493]
In the `config.md` the configuration for the output format is described as
~~~
    // The format of the method count output, either "list", "tree", "json",
    // or "yaml".
    format = OutputFormat.LIST
~~~

First, the samples ("list", "tree", "json","yaml") does not map to the format of e.g. `OutputFormat.LIST`.
This should be a better wording, e.g. use `OutputFormat.LIST, OutputFormat.TREE, ...`

Second, I had to add `import com.getkeepsafe.dexcount.OutputFormat` in my gradle file.
Please add this to the sample.

And last, a Feature request: 
Support multiple output formatter, e.g. with `format = OutputFormat.TREE;OutputFormat.JSON`

**Comment by benjamin-bader** [comment]
yeeeaaahhhh I definitely haven't spent very much effort on documentation.  That comment specifically _used_ to be true, but since the Java rewrite in 2021, it no longer applies.  At the time of writing you could actually just use strings like "list", "tree", etc - made it less ambiguous in the rewrite but totally forgot about that bit of doc.  I'll leave this open as a reminder to fix when I get back from vacation.

I'm not spending my dev cycles on this project lately, so won't promise multiple output format support, but I'll take a look - if it's simple to add and doesn't break things, then sure, why not.

**Comment by bekuno** [comment]
> I'll leave this open as a reminder to fix when I get back from vacation.

I created a PR for it.
For now I wish you a nice vacation.
 
> I'm not spending my dev cycles on this project lately, so won't promise multiple output format support, but I'll take a look - if it's simple to add and doesn't break things, then sure, why not.

Sure, this was only a idea, it is not necessary for me.
