### ISSUE TITLE
Feature request: count before generating Dex?

### ISSUE THREAD

**Issue by danielesegato** [KeepSafe/dexcount-gradle-plugin#90]
If the Dex generation fail because you have more then 65k method this plugin doesn't print anything, thus there's no way of figuring out which part of the app is using the most methods.

I guess you count the methods/fields over the generated Dex file so you probably can't do much about it. Worth a try anyway.

Thanks

**Comment by benjamin-bader** [comment]
You are correct on both counts - a dex failure during build will prevent the plugin from running, because what it does is examine the .dex output to see what made it in.

It's an unfortunate and mildly ironic failure mode, for sure.

I can't think of an accurate way to provide counts prior to dexing though, because a) Proguard, and b) dex deduplicates common methods, e.g. from shared transient dependencies.  If one were to have a good idea, I'd be happy to hear it!

**Comment by danielesegato** [comment]
@benjamin-bader thanks anyway!
